name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  test-macos:
    name: Swift ${{ matrix.swift }} on macOS ${{ matrix.macos }} with Xcode ${{ matrix.xcode }}${{ matrix.traits != '' && format(' and --traits {0}', matrix.traits) || '' }}
    runs-on: macos-${{ matrix.macos }}
    env:
      DEVELOPER_DIR: "/Applications/Xcode_${{ matrix.xcode }}.app/Contents/Developer"
    strategy:
      fail-fast: false
      matrix:
        include:
          - swift: "6.0"
            xcode: "16.0"
            macos: "15"
            traits: ""
          - swift: "6.1"
            xcode: "16.3"
            macos: "15"
            traits: ""
          - swift: "6.1"
            xcode: "16.3"
            macos: "15"
            traits: "Xet"
          - swift: "6.2"
            xcode: "26.0"
            macos: "26"
            traits: ""
          - swift: "6.2"
            xcode: "26.0"
            macos: "26"
            traits: "Xet"
    timeout-minutes: 10
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Cache Swift Package Manager dependencies
        uses: actions/cache@v5
        with:
          path: ~/.cache/org.swift.swiftpm
          key: ${{ runner.os }}-xcode-${{ matrix.xcode }}-swift-${{ matrix.swift }}-${{ matrix.traits == '' && 'xet-off' || 'xet-on' }}-spm-${{ hashFiles('Package.swift', 'Package@swift-6.0.swift', '**/Package.resolved') }}
          restore-keys: |
            ${{ runner.os }}-xcode-${{ matrix.xcode }}-swift-${{ matrix.swift }}-${{ matrix.traits == '' && 'xet-off' || 'xet-on' }}-spm-

      - name: Build
        run: swift build${{ matrix.traits != '' && format(' --traits {0}', matrix.traits) || '' }}

      - name: Test
        run: swift test${{ matrix.traits != '' && format(' --traits {0}', matrix.traits) || '' }}

  test-linux:
    name: Swift ${{ matrix.swift }} on Linux${{ matrix.traits != '' && format(' and --traits {0}', matrix.traits) || '' }}
    runs-on: ubuntu-latest
    container: "swift:${{ matrix.swift }}"
    strategy:
      fail-fast: false
      matrix:
        include:
          - swift: "6.0.3"
            traits: ""
          - swift: "6.1.3"
            traits: ""
          - swift: "6.1.3"
            traits: "Xet"
          - swift: "6.2.3"
            traits: ""
          - swift: "6.2.3"
            traits: "Xet"
    timeout-minutes: 10
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Build
        run: swift build${{ matrix.traits != '' && format(' --traits {0}', matrix.traits) || '' }}

      - name: Test
        run: swift test${{ matrix.traits != '' && format(' --traits {0}', matrix.traits) || '' }}
